### ISSUE TITLE
Error while opening thinker.ini file

### ISSUE THREAD

**Issue by DesolationStone** [induktio/thinker#11]
![image](https://user-images.githubusercontent.com/80346254/110498913-09d30080-80f8-11eb-93f6-26d7d172e794.png
![Immagine 2021-03-09 165401](https://user-images.githubusercontent.com/80346254/110498937-0fc8e180-80f8-11eb-9e5f-fdb510310141.png)

For some reason thinker mod don't want to launch, I follow all instructions but I still have this error

**Comment by induktio** [comment]
No idea about this one. Looks like some kind of an installation issue.

**Comment by DesolationStone** [comment]
I don't know I don't know, maybe windows problems?
All others mod runs very well

**Comment by pianoslum** [comment]
Is thinker.ini in the folder?

**Comment by DesolationStone** [comment]
I've resolved the problem: simply start the exe from the folder, not from the search bar as I previously doing
