### ISSUE TITLE
Why stop vehicle when at destination?

### ISSUE THREAD

**Issue by tnevolin** [induktio/thinker#18]
https://github.com/induktio/thinker/blob/87ae1ea24f254c8dd674eb8dcea445ddd7c9b1cb/src/game.cpp#L403

Don't understand why you explicitly skip vehicle when at destination.
What if this is sea colony still having some movement left? Why not let it to build a base same turn?

**Comment by induktio** [comment]
Under normal circumstances units should not be issued movement orders to the same tile they are occupying. Also colony pods should evaluate current tile suitability for bases before movement code is checked. Is there any scenario where this behaviour becomes a problem?
