### ISSUE TITLE
Combat move changed

### ISSUE THREAD

**Issue by tnevolin** [induktio/thinker#21]
[test_combat_move.zip](https://github.com/induktio/thinker/files/6291109/test_combat_move.zip)

2.4 had pretty logical combat move.
When I play this save with 2.4 believers' scouts in base attack my troops staying right next to their base.

When I play same save with latest code they get out of the base without attacking my forces leaving base undefended.

I blame this code. When I comment it out the logic returns to normal.
https://github.com/induktio/thinker/blob/ac4852e37634e22c7e11bd15451d3834a3e09f47/src/move.cpp#L2142

Keep in mind that I have only tested 2.4 from your release. There is no release for current commit. So you may want to retest it yourself to confirm the problem.

**Comment by induktio** [comment]
combat_move received a massive rewrite, for the most parts it's mostly finished and near release state. At least for now. Pull the latest commit and see what you'll notice there. There's also a surprise GUI feature that will be announced in this new release.

**Comment by induktio** [comment]
This new build also did many tweaks on combat unit movement and some smaller bugfixes. I changed the formula that determines scouting priorities so now it should be quite robust for many situations. Some other changes include AIs building Punishment Spheres and using drill to aquifer command occasionally. Another idea was also that base_tile_score will start penalizing locations that are too cllose to poles so the AIs will expand towards the center of the map.
