### ISSUE TITLE
Exposing methods in headers

### ISSUE THREAD

**Issue by tnevolin** [induktio/thinker#22]
This is just a request for integration ease. I like to reference your functions to reuse your functionality without modifying your files as much as possible but sometimes they are not exposed in headers so I have to ether modify header or rewrite it completely. Would you mind exposing all functions if it is not much trouble? Thank you.

**Comment by induktio** [comment]
Well, I might do some changes if they are relevant to making the code clearer to read but as a general basis I can't make development decisions on how other forks might maintain that code. If you change some stuff in a forked version, any maintainability issues arising from it are not really relevant to this mod's development. It's already enough time-consuming dealing with reverse engineering binaries. That's just how forking works usually. Some things could be refactored but I'm not convinced how relevant this is for Thinker mod's users.

**Comment by tnevolin** [comment]
Not relevant.
