### ISSUE TITLE
VehBaseUnit is hardwired

### ISSUE THREAD

**Issue by bvanevery** [induktio/thinker#37]
terranx_enums.h contains a hardwiring of predefined units in alphax.txt.  Nobody ever guaranteed that these units are as claimed.  It may be of no consequence to Thinker itself, but it is of consequence to those of us who mod units in alphax.txt.  For example in a game where I combined Thinker with my SMACX AI Growth mod, I got illegal creation of a Clean 3-Res Transport every game, because I have it in the "unit = 3" slot (counting from 0).  Thinker assumes that's always a Transport with no other capabilities, and that's not true in general.
https://alphacentauri2.info/index.php?topic=21768.msg133377#msg133377

The stock binary, in contrast, does not require a Transport unit to be defined in alphax.txt at all, for Transports to appear in the game.  It somehow designs a plain Transport if such is needed.

**Comment by induktio** [comment]
This game engine supports only limited moddability and as such it uses hardcoded IDs for various items all over the place. This particular header just follows the definitions that the game engine uses for various basic units. Since you didn't specify how this unit got created, my suspicion is that it got spawned by some of the vanilla engine code that just happens to assume a transport foil is always available with unit id=3. Unless you actually see a base producing this unit, it's probably spawned by some time_warp or goody_box related code. Changing these hardcoded definitions isn't practical and isn't planned anyway. If modders need to define additional special units, the best practise is to add them to the end of the list and not change the pre-existing IDs.

**Comment by bvanevery** [comment]
Most operative comment 1st:
> Probably it should involve an additional check if the unit prereq tech is discovered 

That would help.  And should be done for every predefined unit.

> but it can run into problems if there are no valid transport prototypes available even if the transport module tech is discovered. 

Transport module alone doesn't mean you can make a _ship_.  You must also have a foil or cruiser chassis.  Surely, any given code has to handle the possibility that various ships aren't allowed yet.

>This already causes problems with sea colony pods, since sometimes the prototype is not created by the vanilla game. That's why the AIs are sometimes forced to use Sea Escape Pod prototypes.

Sea Escape pods are used when Aliens and Humans depopulate each other's bases.  No other time.  I've never seen the stock binary produce a Sea Escape Pod in any other circumstance.  I assume they did it for narrative reasons (to get to call it "Escape"), for moddability (even if ultimately they didn't change anything), and to separate implementation concerns (lest they stir up new bugs in old code). 

As for moddability stuff:

> This game engine supports only limited moddability and as such it uses hardcoded IDs for various items all over the place.

That's a regrettable practice that might be worth cleaning up at some point.  I haven't stared at the code long enough to know how easy that would be to do.

> my suspicion is that it got spawned by some of the vanilla engine code that just happens to assume a transport foil is always available with unit id=3. 

I ran 2 test games using the stock binary only.  Although it's not definitive, no modded Clean 3-Res Transport was created.  I have also never observed this problem in my own .txt modding work with the stock binary.  Whereas, Thinker always creates this unit in the course of play.

AFAICT the stock binary simply does not require that Transport unit to be any particular thing.  Other units, such as mindworms, the various Unity units, and the Battle Ogres, yes the stock binary expects them to be very specific things.

> Unless you actually see a base producing this unit,

It is well documented in that thread that Thinker bases produce the units.  At least, the 2nd, 3rd, 4th etc. units are definitely so produced.  I'd have to go back and look at whether I have a save of how the 1st unit came to be.  I'm not sure what time_warp is (cloning? dimensional rift?), but as for whatever "goody_box" is... random pops from supply pods generally produce Unity units, not plain Transports.   I bet "goody_box" is not supposed to deal with the first few units in the alphax.txt #UNITS list.  Why would you be awarded a Scout Patrol, for instance?

>  the best practise is to add them to the end of the list and not change the pre-existing IDs.

It is not actually the best practice when working around bugs in the stock binary.  Disabling plain Transports works around a problem in the stock binary where it obsesses about producing them.  The problem with changing Thinker's predefined unit behavior compared to the stock binary, is that then you're expecting alphax.txt files to be written specifically for Thinker's benefit.  That's your prerogative as a modder, but it doesn't count as a best practice, because it puts an additional implementation burden on other modders.  They have to ship 2 files and test 2 different cases for bugs, if they're going to support Thinker.  The path of least resistance is to blow Thinker off and not worry about it.  It would be better if Thinker and the stock binary both worked the same way, i.e. Transports and Sea Formers are dynamically conjured from the ether as needed. 

Also, predefined unit slots are a bit precious in the stock binary.  If you have too many, things get weird in the game.  There are good reasons to have additional predefined units, and not necessarily in small quantity either.  They're one of the main tools for reprogramming the stock binary to do something more appropriate and challenging.

**Comment by induktio** [comment]
I updated the comment later to reflect that I noticed one of the AIs was indeed producing a modified transport foil and the reason was stated there. So in this case I don't claim it was spawned by a supply pod or similar. Also "Sea Escape pods are used when Aliens and Humans depopulate each other's bases. No other time." is not accurate. For example the first sea colony pods you get when spawning as an aquatic faction are actually Sea Escape Pods. At the spawning phase it's unlikely any custom prototypes are available.

So it appears your mod does allow building both foils and transport units straight away? I don't see the reasoning then for changing the transport foil prototype to something entirely different. To use the transports, players need to have *some* kind of a prototype to produce. Btw, Thinker checks if *both* ships and transport "weapons" are available before producing them.

If there are no valid basic transport prototypes defined, then the AIs would also need extra code for creating suitable prototypes. That uses an additional faction-specific design slot. If the default Transport Foil prototype prereq were set to Disable it could function as a fallback for AIs only if they don't have other suitable prototypes available. And also avoid any issues in the vanilla game if it happened to assume a particular prototype in that design slot or if the vanilla AI produced too much of them. It looks like your mod currently doesn't provide any predefined transport unit that can be produced right away even if the tech prereqs are set to none, unless I misread something.

**Comment by bvanevery** [comment]
> the first sea colony pods you get when spawning as an aquatic faction are actually Sea Escape Pods.

I'll be darned.  I must have noticed that at some point, but I haven't noticed in awhile.

![Pirates start with Sea Escape Pods](https://user-images.githubusercontent.com/734930/155641374-e67a4948-955b-46f5-b87e-cde86b7e5fcc.jpg)

> At the spawning phase it's unlikely any custom prototypes are available.

I modded my Sea Escape Pods.  They're Clean units, same as Sea Colony Pods in my mod.  Game starts with Clean Reactors available.  Simple colony types have a special dispensation that they're Clean and don't cost anything extra for being Clean.  This helps stock AI with early SUPPORT problems.

> So it appears your mod does allow building both foils and transport units straight away?

Yes.  It solves AI performance problems with limited land, as well as some Probe Team and Former tech dependency problems.  There really isn't any good narrative reason for avoiding ships.  This is not 4000 B.C. and it's not Civ II.  SMAC mostly aped its tech tree from Civ II because it was a game progression that "worked" for the most part.  That doesn't mean it was credible or worked well in all cases.  For instance in Civ II, getting stuck on an ice floe at one of the poles was a pretty "legendary" start.

I implement this by:
`Foil,M1,      Skimship,M1,   Hoverboat,M1,   Coastal,M1,   5, 1, 0, 0, 2, 4, None,  Megafoil,M1,       Superfoil,M1,`
and
`Troop Transport,      Transport,      0, 7, 3, -1, None,`

Anyone can do anything with a foil chassis, or a Transport package.  No actual unit is predefined.  The stock binary somehow takes these ingredients and coughs up a Transport foil with them.

>  I don't see the reasoning then for changing the transport foil prototype to something entirely different. 

It saves a predefined unit slot, in a place that is not needed by the stock binary for anything.  Predefined unit slots are a bit precious.

Failing to provide a plain Transport, and instead providing something that isn't available until E4 Bioadaptive Resonance, seems to stop the AI from obsessing about "making too many transports" for a good while.  This is a huge problem for the Pirate AI, because it is so dependent upon ferrying units.

>   To use the transports, players need to have _some_ kind of a prototype to produce. 

No they don't.  Here, let me start a game with a non-Pirate faction.  SMACX AI Growth mod version 1.52, Morganites Turn 1:

![Morganites can make a Transport](https://user-images.githubusercontent.com/734930/155643974-420c8774-dc33-4bf4-b475-47a1025738ac.jpg)

My alphax.txt has no "plain Transport foil" unit in it.  

> If there are no valid basic transport prototypes defined, then the AIs would also need extra code for creating suitable prototypes. 

Stock binary has such code.  Also happens for Sea Formers, but it's buggy and sometimes doesn't work.  That's why I have Clean Sea Formers as a backup.

> That uses an additional faction-specific design slot.

This, I haven't much noticed or paid attention to.  Nor what the consequences might be.  I'm not sure it's bad:

![Morganic starter designs](https://user-images.githubusercontent.com/734930/155645381-c7041db7-a7b9-4adf-a96b-38c8434ea0e4.jpg)

So let's say later in the game, I never want to make a "plain Fission Transport foil" ever ever again.  Well it just goes faction-specific bye-bye.  Not stuck with it as a base predefined unit forever.  That sounds good.  Saves a slot as the game progresses and there are more designs cluttering things.  Only got so many slots.

> avoid any issues in the vanilla game if it happened to assume a particular prototype in that design slot

My testing of the stock binary over 3.5+ years is extensive.  Let's see, how many mod releases have I changed the Transport predefined unit to something else?  Hmm, in release 1.39 quite awhile ago, that Transport became a Clean Transport.  There were no bugs for making it Clean, but of course it was a Transport.  And Clean Reactors were available from the beginning of the game, with me doing that sort of thing.  Unlike 3-Res armor, which definitely isn't.

What else... in version 1.33, even longer ago, I had that slot being used for a _Cruiser_ Transport.  Didn't cause any issues, and of course Cruisers are not available at game start.  Also in that release, the notation "- Transport: now occupies the very last position in the predefined units list, to try to curb the Pirate AI's obsession with it."  Nothing broke.  I think this indicates the stock binary doesn't assume Transports are in a particular slot, and is robust about checking the tech requirements of a predefined unit.

> or if the vanilla AI produced too much of them. 

I've been around and around and around and around with that.  All kinds of Transport designs, trying to head it off.  I can see if a "disabled Transport" somehow affects Pirate production behavior in the stock binary, but I'm not expecting much.

Here's what I think really happens, currently.  You can't stop a plain Transport from existing if its tech prereqs are available, so they are still produced in substantial numbers.  But, they get killed.  Then by C3 Advanced Subatomic Theory when Plasma armor is available, my predefined unit table tells the stock AI, "go build you some Clean Plasma Transports".  And it does that.  A _lot_.  And it stops making the plain ones anymore, because it's an inferior design.

When E4 Bioadaptive Resonance becomes available, my predefined unit table tells the stock AI, "go build you some Clean 3-Res Transports".  And it does that.  A _lot_.  A bit better chance to hold off an Isle, and the ship doesn't actually cost any more.

These 2 ship designs hold up better defensively, and they don't impact SUPPORT.  So even though the AI is obsessing, there's some defensive value to it, and it's not getting SUPPORT crippled.  The early plain Transport stuff has a regrettable impact, but it's still better to have the tougher more expensive ships built in quantity later.  Otherwise if I defined a Clean Transport, the AI would just see that as a cheaper ship and produce tons of 'em.  I think it's more of a waste of minerals, building stuff that has no defense.  Like, what if it's carrying cargo?  One sinks; the other has a chance to live.

**Comment by induktio** [comment]
I'm not sure what you're trying to claim in response here: "To use the transports, players need to have some kind of a prototype to produce. [...] No they don't". Every vehicle existing on the map needs to have a some kind of a prototype assigned to it. This is also the ID used when it is selected for production. So obviously this prototype needs to exist either in the pre-defined units or faction-specific design slots. There's no way around it.

In that specific save file it doesn't look like the AIs have any faction-specific transport prototypes created, so it appears the vanilla code didn't create the custom prototypes in this case, for reasons unknown. Generally editing the pre-defined units in an arbitrary fashion is not really supported by the game engine given the hardcoded IDs used. The table is named "Basic Units". Thinker code also relies on fixed IDs for many basic units. I may look into whether there could be more code added for creating extra prototypes, but this may or may not be added to Thinker. It might also be useful for dealing with the non-existent Sea Formers issue.

The obvious fix here is to keep the default Transport Foil prototype in alphax.tst pre-defined units, and not add any abilities on it that cannot be validly produced when the transport package/foil chassis features become available. It can be also set to Disable prereq to prevent the vanilla AI from producing them.

**Comment by bvanevery** [comment]
> The obvious fix here

Workaround.  A _fix_ would be handling it the way the stock binary does, not hardwiring things.  "Combo" mods need things to work the way they work in the stock binary, to the extent that anyone messes heavily with predefined units.  I get that you're not excited about writing code in support of that, that you see Thinker mostly as a standalone deal.  Maybe in the future I'll provide a patch.  But as I've only just begun to look at your code, I can't promise anything.  I can't yet tell what's easy or hard to do, or even how anything in general is done.

Hopefully you do agree at least that the tech prereq for a predefined unit should be checked, and that this is low hanging fruit.

**Comment by induktio** [comment]
Well, I'm not convinced the stock binary will consistently create transport foil prototypes for the AI factions if the default one is not available. It didn't seem to happen in the savegame either. As it stands now, the prototype picker has a list of fallback default prototype choices whenever it will looks to produce given triad/weapon combo. These units are: BSC_SCOUT_PATROL BSC_COLONY_POD BSC_SEA_ESCAPE_POD BSC_FORMERS BSC_SEA_FORMERS BSC_SUPPLY_CRAWLER BSC_TRANSPORT_FOIL BSC_PROBE_TEAM.

So changing these prototypes from the defaults may currently cause it to produce units it should not produce yet. It may be possible to force the AI design missing prototypes by using propose_proto function, but I haven't tested it yet for these additional circumstances. It's not an ideal situation, but the game engine relies on fixed IDs for many of these units anyway.

**Comment by bvanevery** [comment]
> Well, I'm not convinced the stock binary will consistently create transport foil prototypes for the AI factions if the default one is not available. 

It is not actually _desirable_ for the stock AI to create Transports prematurely.  Land is more valuable for all factions except the Pirates.  I can't swear to current Pirate behavior in my current release 1.52, but I don't recall them being crippled in any way.  For one thing, Pirates will at least make Clean Sea Colony Pods early on, regardless of whether they have Transports.  Colonization of the sea is the main job the Pirates should be doing in the early game.

Transport predefines might also be specifically irrelevant to AQUATIC factions.  I doubt I've crippled the Pirates but I can check.

The only exit case that is important, is if a stock AI faction gets a "cramped land start" and fails to free itself of this circumstance via a sea route.  Although, when it makes Clean Sea Colony pods, it _is_ getting partly free of the problem.  I suppose the real acid test would be to forego my usual 30%..50% ocean generation, and try playing a game on a mostly water world.  It is not the design center of my mod and not something I feel terribly responsible for making sure it works, but it would be a pretty thorough test.  If there's no problem in this circumstance, then there is no problem in any circumstance.

Freeing factions by immediate sea access, is something I do in my mod, that you don't do in Thinker.  You're playing with mostly stock rules.  You don't give ships away on Turn 1.  You can have cramped factions just twiddle their thumbs and die.  So if you are greatly worried about sea performance... maybe you'll be persuaded that the vanilla tech tree is bad.

> propose_proto function

I will try to understand it.  Somewhere in between trying to understand Microsoft DirectX-Graphics-Samples, which are probably going to look like hell.

Meanwhile, since running test games requires almost no brainpower, I will try the waterworld.

**Comment by bvanevery** [comment]
SMACX AI Growth mod version 1.53 alpha with stock binary.  Standard map, 30%..50% ocean.  Data Angels end up in worst case and do not produce coastal settlements until MY 2172.  How long until they produce a Transport?
[Roze of the Angels, 2172.zip](https://github.com/induktio/thinker/files/8148723/Roze.of.the.Angels.2172.zip)
![2 new coastal cities](https://user-images.githubusercontent.com/734930/155884581-4e929f7b-f624-414f-8b72-6d7376fffac1.jpg)
MY 2179.  Angels begin making a Foil Probe Team, which is not insane but rather expensive for them.  Under what circumstances would the AI rationally decide to build a Transport?  At this time, wouldn't it be better to build a Clean Sea Formers?
[Roze of the Angels, 2179.zip](https://github.com/induktio/thinker/files/8148736/Roze.of.the.Angels.2179.zip)
![can't stop the probes](https://user-images.githubusercontent.com/734930/155884748-b72f62c1-ed27-4f82-a454-d0027bc97464.jpg)
MY 2188.  Angels start producing a 2nd Foil Probe team in the other coastal city.  They have 2 land colonists and in principle are pursuing a policy of land settlement, but in practice are milling those 2 units about and not settling them.  It may be that the stock binary's colonization algorithm is too inferior to provide a solution, regardless of Transports.  After all, the real short term answer is a Clean Sea Colony Pod, or perhaps some exploration of uncharted waters.
[Roze of the Angels, 2188.zip](https://github.com/induktio/thinker/files/8148740/Roze.of.the.Angels.2188.zip)
![lack of extrication](https://user-images.githubusercontent.com/734930/155884999-1cc9146a-44d7-475e-bb9a-6cd0dccdcfe0.jpg)

**Comment by induktio** [comment]
Transport Foils are needed the moment sea colonization or invasions begin for Thinker AIs, otherwise the AIs might do some weird things. There are some very specific strategies that rely on them. The reason I say the stock binary is incosistent in creating these prototypes is because they don't appear with any consistency for all factions in my tests. These prototypes are supposed to be added via consider_designs > propose_proto > make_proto function calls (vanilla game logic) which are executed every turn for every AI faction. Even when I add code to call propose_proto with explicit parameters for transport foils, the prototype seems to be created only sometimes. The reasons for this are unknown, so that's a problem.

**Comment by bvanevery** [comment]
Yet, the stock binary seems to create Transports when they're really required for something.  MY 2151, SMACX AI Growth mod, stock binary.  Tiny map.  I followed the plight of the greatly disadvantaged Morganites.  They used the Unity Transport they were gifted at the beginning of the game, to settle a nearby land colony.  They also cheated and Terraformed UP their starting island.  Caretakers trashed the Morganic city on the other island.  Then used Transports to trash Morgan's capitol.  They built 2 of them, did not have any captured Isles, and did not have any Unity Transports.
[Morgan of the Morganites, 2151.zip](https://github.com/induktio/thinker/files/8149292/Morgan.of.the.Morganites.2151.zip)
![Caretaker assault](https://user-images.githubusercontent.com/734930/155896635-84cd1fce-4b79-45b6-af64-e669b6eaa2a7.jpg)

In another waterworld game on a Standard map, I learned that the Cult doesn't have to worry about this.  They'll capture Isles and use them to do their assaults.

**Comment by bvanevery** [comment]
In my mod I'm going to try Clean Transport in the Transport slot, and Clean Sea Formers in the "*Sea Formers" (disabled) slot.  And hope it doesn't send the Pirates right back to making ridiculous numbers of wasteful early Transports.

**Comment by bvanevery** [comment]
Unfortunately making the Clean Transport available in the stock binary, causes the Pirates to engage in extreme foolishness.  34 units produced, and the vast majority aren't doing anything useful.  They tend to sit around in bases with nothing to do, just Holding.
[Svensgaard of the Pirates, 2210.zip](https://github.com/induktio/thinker/files/8153866/Svensgaard.of.the.Pirates.2210.zip)
![excessive Pirate transports in stock binary](https://user-images.githubusercontent.com/734930/155995678-d787dc43-eee8-483a-bc72-327a3e758b55.jpg)
![typical non-use of Transports in Pirate base](https://user-images.githubusercontent.com/734930/155995980-dcea5a90-bef8-4cb6-a505-2ffcb3ab779e.jpg)

Also turns out that as good an idea as Clean Plasma Transport and Clean 3-Res Transport are for other factions, these units are in the Conquer part of the tech tree.  The Pirates in my mod are an Explore Build faction that pursues Wealth.  So they don't learn how to make the more useful defensive units for quite some time.

I will try the "fake disabled" unit idea.

**Comment by bvanevery** [comment]
"Fake Transport" (disabled) does prevent the stock binary from obsessing about Transports, or creating them at all, absent some "demonstrative need".  Some factions that were always under AI control, did come up with them.  The Pirates never did, which was the objective.  In MY 2244 they finally learned Plasma armor despite their Explore Build focus.  They started making the predefined Clean Plasma Transport unit in large quantities.
[Svensgaard of the Pirates, 2244.zip](https://github.com/induktio/thinker/files/8157362/Svensgaard.of.the.Pirates.2244.zip)
![first Clean Plasma Transport](https://user-images.githubusercontent.com/734930/156070222-87993c63-46db-414b-9717-24fede40c8cc.jpg)
Their empire seems to have done just fine with this production strategy.  They made a lot of spammy Synth Foils that fended off hostile, nearby Usurpers, even lacking Laser armament.  Probably because the Usurpers were mostly busy conquering on land and not giving the Pirates their undivided attention.  Which totally counts; my whole philosophy of the Pirates is they have a huge moat and are a PITA to actually conquer.

The Pirates did make 2 Clean Colony Pods early on, that lacking Transports to take them somewhere, never turned into cities.  That's not a problem though, as they don't use up any SUPPORT and aren't especially expensive to make in my mod.

So I have 2 further questions:
1. Does this "Fake Transport" (disabled) actually work with Thinker?  To be tested.
2. Would offering a Clean Synth Transport be an acceptable strategy for the Pirates?  It would be available almost immediately.  Thus the Pirates would start obsessing almost immediately.  Other factions might obsess too.  Does it cause the stock binary to use different early game strategies?  And are those strategies any better than what the Pirates did this game?
