### ISSUE TITLE
Miriam doesn't build a sane amount of satellites

### ISSUE THREAD

**Issue by ByrelMitchell** [induktio/thinker#52]
I just finished up an After Action Report over on the alphacentauri2 forum, where Miriam conquered the entire world aside from me. She was the first faction to research Orbital Spaceflight (around 2250), and got Advanced Spaceflight around 2284. I won the game in 2306 with her having built exactly 1 Hydroponics Lab and 2 Power Transmitters, both near the end of the game. At that point she had over 100 bases; there's just no way this is close to optimal.

It's not a bug, obviously, but I think the AI of a successful aggressive faction with a ton of bases should actually prioritize satellites very heavily. They're the build-option that scales best with conquest, after all.

Edit: I can provide save files for a lot of different points in this game if they would be helpful.

**Comment by induktio** [comment]
There might be some kind of an issue with the base production code if it indeed built so few satellites since it's not optimal. Some savegame in the timeframe after Miriam got the techs to build the satellites would be needed to look into it.

**Comment by ByrelMitchell** [comment]
[Marr of the Usurpers, 2253.zip](https://github.com/induktio/thinker/files/10902809/Marr.of.the.Usurpers.2253.zip)
She already has Orbital Spaceflight in this save; not sure when exactly she got it, but it wasn't more than 10 turns before this.

[Marr of the Usurpers, 2284.zip](https://github.com/induktio/thinker/files/10902796/Marr.of.the.Usurpers.2284.zip)
I don't have infiltration on her in this save, but if you rush a probe on the left side of my island, it's easy to infilitrate next turn and check that she has advanced spaceflight.

**Comment by induktio** [comment]
It seems like some kind of an issue with the build priority system. Might be related to the lack of Aerospace Complexes on many bases. Have to look into more detail on it later.

**Comment by induktio** [comment]
Alright, uploaded a new develop build that addresses some of these things. At least the other idea mentioned in #53 is very useful considering the various defense bonuses provided mainly by AAA garrisons.

* Satellite build priorities are reworked to start aerospace complex and satellite production sooner.
* AI sometimes builds needlejets with dissociative wave special ability when AAA ability is also available.
* AI is capable of longer range orbital insertions whenever the tech or Space Elevator is available.
* AI should build Tachyon Fields in border bases more often.
