### ISSUE TITLE
AI building a foil probe on a tiny inland lake with no outlet or contested cities

### ISSUE THREAD

**Issue by ByrelMitchell** [induktio/thinker#54]
[Screenshot 2023-03-09 122111](https://user-images.githubusercontent.com/44025439/224106058-1a8d94af-38e0-4653-922a-1171e00c6fc4.png)

The AI is building a foil probe in Laborer's Utopia that will be completely useless to him.

[Zakharov of the University, 2224.zip](https://github.com/induktio/thinker/files/10934289/Zakharov.of.the.University.2224.zip)

**Comment by induktio** [comment]
This was probably some kind of an isolated incident. Something like this might happen if the land altitude near the base was changed after the base began building the unit. Let me know if it happens more often though.
