### ISSUE TITLE
[Thinker 3.6] Resolution Distortion with PRACX

### ISSUE THREAD

**Issue by ParagonAlex** [induktio/thinker#56]
With PRACX installed, launching via the thinker.exe causes a blown up, distorted resolution which obfuscates the UI/menus. Tweaking the ini resolution settings manually or attempting windowed mode does not help. I have tried clean installs, either starting with PRACX or installing it over Thinker. Same result.

**Comment by induktio** [comment]
Might need to get some additional information about the setup. Which Windows version is used here using or is the game running under Wine for example?

**Comment by ParagonAlex** [comment]
I'm just running Windows 11, native. No comparability mode or anything
either.

**Comment by induktio** [comment]
Okay, hard to say if that Windows version affects the game. Have you checked if this error occurs when you run either PRACX or Thinker but not both at the same time? Otherwise I don't have ready solutions for it. There might be some other reports on PRACX repo about resolution issues but not sure.

**Comment by ParagonAlex** [comment]
I've run the game with just PRACX. Works fine. Also with just Thinker, but
the issue occurs only with both. I'll be sure to check out the PRACX side
of things too just in case though.
