### ISSUE TITLE
Hunter-Seeker Algorithm is bypassed

### ISSUE THREAD

**Issue by JaggedOne** [induktio/thinker#64]
The last game I played, I had the _Hunter-Seeker Algorithm_ Secret Project, yet Drone Probe units still infiltrated my cities. I read the notes about enhanced probes in the documentation, but it did not specifically say, nor did I understand it to imply, that the _Hunter-Seeker Algorithm_ could be overridden.

Is this functioning correctly ?

Thanks !!!

**Comment by induktio** [comment]
Definitively enhanced probes should be able to bypass Hunter Seeker Algorithm, although they still have higher rates of failure than normal, so it seems to be working as intended. If you look the infiltrating unit description, it should mention Enhanced attribute. This is from expansion help file: "Renders your units and bases completely immune to probe team infiltration, unless the team is equipped with the Algorithmic Enhancement special ability."

In other cases Hunter Seeker Algortihm should destroy the infiltrating unit. It should be also possible for certain custom faction to grant this attribute on probes but it should not be the case here.

**Comment by JaggedOne** [comment]
Crap, you're right, I completely missed the exception in the description
for Hunter-Thinker !!
My bad. Thanks for straightening me out !!!!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
