### ISSUE TITLE
Hurry partial payment displays wrong amount ?

### ISSUE THREAD

**Issue by JaggedOne** [induktio/thinker#65]
This is really a nit, but I just wanted to see if you knew about it and it was the way you wanted it. It concerns "hurrying" production. I will use the numbers from my current game. 

_Greater Intertwining can The Citizen's Defense Force with 404 credits.
Minimum cost to hurry for next turn completion is 344 credits.
We have 289 credits._

If I click "Make Partial Payment", a window comes up that says

_ENTER PAYMENT AMOUNT (0-289)_
Below this it says _PAYMENT_:  and the amount 344 is in the box.

The non-Thinker (original GOG) game displays 289 in the box after PAYMENT:, which makes sense to me.

I'm not saying this is a bug, and yes it is really picky. :)

**Comment by induktio** [comment]
Yeah I think it's an oversight since the game would not allow paying for more than you have credits available. On the next update it could be changed to default to the amount of credits available if the minimal hurry cost exceeds it.
