### ISSUE TITLE
hang in mod_enemy_move

### ISSUE THREAD

**Issue by OrangeTabbyIsNotAvailable** [induktio/thinker#66]
[hang.sav.gz](https://github.com/induktio/thinker/files/14817319/hang.sav.gz)

Attached is the file I mentioned in the Steam discussion group. It hangs on my system (running via a couple of different Wine and Proton versions) once you press the next move button.

The hang seems to be related to my design workshop artillery vehicle. I wasn't having any problems until I created them. Taking manual control of the vehicle seems to side step the issue.

After turning on the debug flag it seems to be related to the mod_enemy_move() method. These vehicles seem to take the final return, which is the call to the game's enemy_move() method. This method returns VEH_SKIP.  Forcing mod_enemy_move()'s return code to be VEH_SYNC also side steps the issue. 

Thanks!

**Comment by induktio** [comment]
The game probably reaches some unusual state since the vehicle was automated resulting in the infinite loop. This should be fixed in the next build by incrementing iter_count variable on the vehicle if enemy_move does not do anything, so the game stops processing that vehicle for the turn.

**Comment by induktio** [comment]
The game probably reaches some unusual state since the vehicle was automated resulting in the infinite loop. This should be fixed in the next build possibly by changing the return code if enemy_move does not do anything, so the game stops processing that vehicle for the turn.

**Comment by induktio** [comment]
This should be now fixed in the Apr 1 build, as also the issue mentioned in #65.

**Comment by OrangeTabbyIsNotAvailable** [comment]
Thanks! I will check it out.

Apr 1, 2024 11:50:41 AM Induktio ***@***.***>:
